config/routes.rb
Rails.application.routes.draw do
#  resources :indices do
#    resources :prices
#  end
  resources :entities, :constraints => { :id => /.*/ } do
    resources :prices
  end
  resources :lists
  resources :prices
  resources :companies , :constraints => { :id => /.*/ } do
    resources :prices
    collection do
      get 'autocomplete'
    end 
  end
  resources :exchanges
  root :to => 'indices#index'
end

app/models/company.rb
class Company < Entity
    field :industry, type: String
    field :active, type: Boolean
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def autocomplete
    @query = params[:query].upcase.strip
    @company_search = Company.where(ticker: /#{@query}/i)
    respond_to do |format|
      format.json { render json: @company_search, :only => [:ticker, :_id] }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:ticker, :name, :industry, :active, :ignore, :roar, :_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %><br>
    <%= f.text_field :ticker %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :ignore %><br>
    <%= f.check_box :ignore %>
  </div>
  <div class="field">
    <%= f.label :roar %><br>
    <%= f.text_field :roar %>
  </div>
  <div class="field">
    <%= f.label :_id %><br>
    <%= f.text_field :_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Name</th>
      <th>Industry</th>
      <th>Active</th>
      <th>Ignore</th>
      <th>Roar</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.ticker %></td>
        <td><%= company.name %></td>
        <td><%= company.industry %></td>
        <td><%= company.active %></td>
        <td><%= company.ignore %></td>
        <td><%= company.roar %></td>
        <td><%= company._id %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @company.ticker %>
</p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @company.industry %>
</p>

<p>
  <strong>Active:</strong>
  <%= @company.active %>
</p>

<p>
  <strong>Ignore:</strong>
  <%= @company.ignore %>
</p>

<p>
  <strong>Roar:</strong>
  <%= @company.roar %>
</p>

<p>
  <strong>Id:</strong>
  <%= @company._id %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>