config/routes.rb
Rails.application.routes.draw do
#  resources :indices do
#    resources :prices
#  end
  resources :entities, :constraints => { :id => /.*/ } do
    resources :prices
  end
  resources :lists
  resources :prices
  resources :companies , :constraints => { :id => /.*/ } do
    resources :prices
    collection do
      get 'autocomplete'
    end 
  end
  resources :exchanges
  root :to => 'indices#index'
end

app/models/price.rb
class Price
  include Mongoid::Document
  field :date, type: Date
  field :open, type: Integer
  field :high, type: Integer
  field :low, type: Integer
  field :close, type: Integer
  field :volume, type: Integer

  index({date: 1, entity_id: 1})
  belongs_to :entity

  def self.to_to_csv(options = {})
    CSV.generate(options) do |csv|
      columns = Price.fields.keys
      csv << columns
      all.each do |price|
        csv << price.attributes.values_at(*columns)
      end
    end
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show]
  #before_action :set_price, only: [:show, :edit, :update, :destroy]

  def index
    @e_ids = params[:entity_id]
    @e_ids = [@e_ids] if @e_ids.is_a?(String)
    @prices = Price.where(entity_id: {'$in': @e_ids}) if @e_ids
    respond_to do |format|
      format.json
    end
  end

  # GET /prices/1
  # GET /prices/1.json
  #def show
  #end

  # GET /prices/new
  #def new
  #  @price = Price.new
  #end

  # GET /prices/1/edit
  #def edit
  #end

  # POST /prices
  # POST /prices.json
  #def create
  #  @price = Price.new(price_params)

  #  respond_to do |format|
  #    if @price.save
  #       format.html { redirect_to @price, notice: 'Price was successfully created.' }
  #       format.json { render :show, status: :created, location: @price }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @price.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  # def update
  #   respond_to do |format|
  #     if @price.update(price_params)
  #       format.html { redirect_to @price, notice: 'Price was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @price }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @price.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /prices/1
  # DELETE /prices/1.json
  # def destroy
  #   @price.destroy
  #   respond_to do |format|
  #     format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:date, :open, :high, :low, :close, :volume)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :open %><br>
    <%= f.number_field :open %>
  </div>
  <div class="field">
    <%= f.label :high %><br>
    <%= f.number_field :high %>
  </div>
  <div class="field">
    <%= f.label :low %><br>
    <%= f.number_field :low %>
  </div>
  <div class="field">
    <%= f.label :close %><br>
    <%= f.number_field :close %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.number_field :volume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prices</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.date %></td>
        <td><%= price.open %></td>
        <td><%= price.high %></td>
        <td><%= price.low %></td>
        <td><%= price.close %></td>
        <td><%= price.volume %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @price.date %>
</p>

<p>
  <strong>Open:</strong>
  <%= @price.open %>
</p>

<p>
  <strong>High:</strong>
  <%= @price.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @price.low %>
</p>

<p>
  <strong>Close:</strong>
  <%= @price.close %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @price.volume %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>